@include('livewire.admin.members-view', [
    'member' => $member,
    'leftTeamSize' => $leftTeamSize,
    'rightTeamSize' => $rightTeamSize,
    'totalTeamSize' => $totalTeamSize,
    'activeTab' => $activeTab,
    'transactions' => $transactions ?? [],
    'withdrawals' => $withdrawals ?? [],
    'walletBalance' => $walletBalance ?? 0,
    'lockedDaily' => $lockedDaily ?? 0,
    'availableBalance' => $availableBalance ?? 0,
    'binaryUplines' => $binaryUplines ?? [],
    'referralUplines' => $referralUplines ?? [],
    'binaryCommissionTx' => $binaryCommissionTx ?? [],
    'binaryCommissionTotal' => $binaryCommissionTotal ?? 0,
    'referralCommissionTx' => $referralCommissionTx ?? [],
    'referralCommissionTotal' => $referralCommissionTotal ?? 0,
    'dailyCommissionTx' => $dailyCommissionTx ?? [],
    'dailyCommissionTotal' => $dailyCommissionTotal ?? 0,
])
